version: '3.1'

services:
  express:
    build:
      context: .
      dockerfile: Dockerfile.express
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/app
    depends_on:
      - mysql

  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: PDF